name: tampan
description: "hackfest-2024-Tambak Petani Andalan"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  weather: ^3.1.1
  geolocator: ^10.1.0
  baseflow_plugin_template: ^2.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/goggle_icon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins.ttf