name: tampan
description: "hackfest-2024-Tambak Petani Andalan"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon/au.png
    - images/bandeng.png
    - images/icon/camera.png
    - images/fish_farmer.png
    - images/icon/gallery.png
    - images/icon/goggle.png
    - images/icon/identifikasi.png
    - images/ikan_terkena_bakteri.png
    - images/logo.png
    - images/icon/res.png
    - images/icon/sun.png
    - images/icon/unknown.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins.ttf